### ISSUE TITLE
Fix logging error in jagr-gradle startup

### ISSUE THREAD

**Issue by alexstaeding** [sourcegrade/jagr#124]
The following error occurs every time the jagr-plugin plugin is loaded. Logging to file must be disabled when executing from Gradle.

(Optionally add a nice way of choosing this via the launcher api)

```
2022-10-03 20:59:55,097 Daemon worker ERROR Cannot access RandomAccessFile java.io.FileNotFoundException: logs/latest.log (No such file or directory) java.io.FileNotFoundException: logs/latest.log (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
	at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory.createManager(RollingRandomAccessFileManager.java:232)
	at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory.createManager(RollingRandomAccessFileManager.java:204)
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:144)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
	at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.getRollingRandomAccessFileManager(RollingRandomAccessFileManager.java:107)
	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:132)
	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:53)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1138)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1063)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1055)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:664)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:258)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:304)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at org.sourcegrade.jagr.launcher.env.LaunchConfiguration$Standard.<clinit>(LaunchConfiguration.kt:36)
	at org.sourcegrade.jagr.launcher.env.Jagr$Factory$DefaultImpls.create$default(Jagr.kt:43)
	at org.sourcegrade.jagr.launcher.env.Jagr$Default.<init>(Jagr.kt:34)
	at org.sourcegrade.jagr.launcher.env.Jagr$Default.<clinit>(Jagr.kt)
	at org.sourcegrade.jagr.launcher.env.Jagr.<clinit>(Jagr.kt)
	at org.sourcegrade.jagr.gradle.extension.GraderConfiguration$1$1.invoke(GraderConfiguration.kt:77)
	at org.sourcegrade.jagr.gradle.extension.GraderConfiguration$1$1.invoke(GraderConfiguration.kt:75)
	at org.gradle.kotlin.dsl.ProjectExtensionsKt.dependencies(ProjectExtensions.kt:178)
	at org.sourcegrade.jagr.gradle.extension.GraderConfiguration$1.invoke(GraderConfiguration.kt:75)
	at org.sourcegrade.jagr.gradle.extension.GraderConfiguration$1.invoke(GraderConfiguration.kt:59)
	at org.sourcegrade.jagr.gradle.extension.GraderConfiguration._init_$lambda$2(GraderConfiguration.kt:59)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
...
	```

**Comment by alexstaeding** [comment]
Fixed by #126
